Part01/SoHyun/S3_17413.java, Part01/SoHyun/S4_10866.java, Part01/SoHyun/S4_1158.java
=> Part1 / 박소현 / 3문제

Part01/JaeHyeon/G3_17299.java, Part01/JaeHyeon/S3_1935.java
=> Part1 / 김재현 / 2문제

Part01/SeMin/B1_9093.java, Part01/SeMin/S2_1406.java, Part01/SeMin/S2_1874.java, Part01/SeMin/S3_17413.java, Part01/SeMin/S4_10828.java, Part01/SeMin/S4_10845.java, Part01/SeMin/S4_10866.java, Part01/SeMin/S4_1158.java, Part01/SeMin/S4_9012.java
=> fix: 누락된 문제 추가 - 세민

Part01/JaeHyeon/B1_11655.java, Part01/JaeHyeon/B2_10809.java, Part01/JaeHyeon/B2_10820.java, Part01/JaeHyeon/B3_10824.java, Part01/JaeHyeon/B4_10808.java, Part01/JaeHyeon/B5_2743.java, Part01/JaeHyeon/G2_1918.java, Part01/JaeHyeon/S4_11656.java
=> Part1 / 김재현 / 8문제

Part01/SoHyun/B1_11655.java, Part01/SoHyun/B2_10820.java, Part01/SoHyun/B3_10824.java, Part01/SoHyun/B5_2743.java, Part01/SoHyun/S4_11656.java
=> Part1 / 박소현 / 5문제

Part02/JaeHyeon/B1_1934.java, Part02/JaeHyeon/B1_2609.java, Part02/JaeHyeon/B2_1978.java, Part02/JaeHyeon/B5_10430.java, Part02/JaeHyeon/S3_1929.java
=> Part 2 / 김재현 / 5문제

Part02/SoHyun/B1_1934.java, Part02/SoHyun/B1_2609.java, Part02/SoHyun/B2_1978.java, Part02/SoHyun/B5_10430.java, Part02/SoHyun/S3_1929.java
=> Part2 / 박소현 / 5문제

Part02/SeMin/B1_1934.java, Part02/SeMin/B1_2609.java, Part02/SeMin/B2_1978.java, Part02/SeMin/B5_10430.java, Part02/SeMin/S3_1929.java
=> Part2 / 류세민 / 5문제

Part02/JaeHyeon/B1_11005.java, Part02/JaeHyeon/B1_11653.java, Part02/JaeHyeon/B2_2745.java, Part02/JaeHyeon/S2_17103.java, Part02/JaeHyeon/S5_11576.java
=> Part2 / 김재현 / 5문제

Part03/JaeHyeon/S1_11052.java, Part03/JaeHyeon/S3_11726.java, Part03/JaeHyeon/S3_11727.java, Part03/JaeHyeon/S3_1463.java, Part03/JaeHyeon/S3_9095.java
=> Part3 / 김재현 / 5문제

PGS/Part01/SeMin/L2_1844.java, PGS/Part01/SeMin/L3_43163.java
=> PGS_Part01 / 류세민 / 2문제

PGS/Part01/SoHyun/L2_1844.java, PGS/Part01/SoHyun/L3_43163.java
=> PGS_Part01 / 박소현 / 2문제

PGS/Part01/JaeHyeon/L2_1844.java, PGS/Part01/JaeHyeon/L3_43163.java
=> PGS_Part01 / 김재현 / 2문제

PGS/Part01/SeMin/L3_43164.java, PGS/Part01/SeMin/L3_84021.java, PGS/Part01/SeMin/L3_87694.java
=> PGS_Part01 / 류세민 / 3문제

PGS/Part02/JaeHyeon/L1_340213.java, PGS/Part02/JaeHyeon/L2_340212.java
=> PGS_Part02 / 김재현 / 2문제

PGS/Part02/SoHyun/L2_340211.java, PGS/Part02/SoHyun/L3_340210.java
=> PGS_Part02 / 박소현 / 2문제

PGS/Part02/JaeHyeon/L1_250137.java, PGS/Part02/JaeHyeon/L2_250135.java, PGS/Part02/JaeHyeon/L2_250136.java, PGS/Part02/JaeHyeon/L3_250134.java
=> PGS_Part02 / 김재현 / 4문제

PGS/Part02/SeMin/L1_250137.java, PGS/Part02/SeMin/L2_250135.java, PGS/Part02/SeMin/L2_250136.java, PGS/Part02/SeMin/L3_250134.java
=> PGS_Part02 / 류세민 / 4문제 

PGS/Part03/JaeHyeon/L2_17680.java, PGS/Part03/JaeHyeon/L2_64065.java
=> PGS_Part03 / 김재현 / 2문제 

PGS/Part03/SeMin/L2_17677.java, PGS/Part03/SeMin/L2_17687.java, PGS/Part03/SeMin/L2_92335.java
=> PGS_Part03 / 류세민 / 3문제

PGS/Part03/JaeHyeon/L2_17677.java, PGS/Part03/JaeHyeon/L2_17687.java, PGS/Part03/JaeHyeon/L2_92335.java
=> PGS_Part03 / 김재현 / 3문제

CTR/HSAT/JaeHyeon/L8_교차로.java, CTR/HSAT/JaeHyeon/L8_플레이페어 암호.java, CTR/HSAT/JaeHyeon/L9_성적 평가.java
=> CTR_HSAT / 김재현 / 3문제 

CTR/HSAT/SoHyun/L8_Intersection.java, CTR/HSAT/SoHyun/L8_PlayfairCipher.java, CTR/HSAT/SoHyun/L9_GradeEvaluation.java
=> CTR_HSAT / 박소현 / 3문제

CTR/HSAT/SoHyun/L10_CommuterBusOrderValidation.py, CTR/HSAT/SoHyun/L10_TaskProcessing.py, CTR/HSAT/SoHyun/L11_CarTest.py, CTR/HSAT/SoHyun/L11_VisitInOrder.py
=> CTR_HSAT / 박소현 / 4문제
